name: Docker Image CI Flask API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image for flask api
      run: docker build . --file Dockerfile --tag flask_api:$(date +%s)
